apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: https://github.com/Maverickme222222/istio-application-manifest.git
              revision: HEAD
              files:
              - path: "application-manifests/config-dev.json"
          # cluster generator, 'child' #2
          - list:
              elements:
                - service: nginx
                  url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Maverickme222222/istio-application-manifest.git
        targetRevision: HEAD
        path: 'application-definitions/{{environment}}/{{service}}'
      destination:
        server: '{{url}}'
        namespace: default