apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: https://github.com/Maverickme222222/istio-application-manifest.git
              revision: HEAD
              files:
              - path: application-manifests/dev/configs.yaml
          # cluster generator, 'child' #2
          - list:
              elements: []
              elementsYaml: "{{ .key.components | toJson }}"
  template:
    metadata:
      name: 'test-{{.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Maverickme222222/istio-application-manifest.git
        targetRevision: HEAD
        path: 'application-definitions/dev/{{.name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default