environment: dev
appName: dev-app
url: https://kubernetes.default.svc
services:
  components:
  - name: nginx
    chart: podinfo
    version: "6.3.2"
    releaseName: component1
    repoUrl: "https://stefanprodan.github.io/podinfo"
    namespace: component1